service: serverless-diary

plugins:
  - serverless-dotenv-plugin # used for injecting variables from .env
  - serverless-plugin-typescript
  - serverless-offline # used for local execution

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: ${opt:stage}
  timeout: 30   # repository wide Lambda timeout
  environment:  # repository wide Lambda env variables
    STAGE: ${self:provider.stage}

functions:
  Root:
    handler: ./src/handlers/index.handler
    description: The root path of the Diary App
    events:
      - httpApi:
          path: /
          method: GET

  AuthRegister:
    handler: ./src/handlers/api/auth.register
    description: Create a new user account
    events:
      - httpApi:
          path: /api/auth/register
          method: POST

  AuthLogin:
    handler: ./src/handlers/api/auth.login
    description: Sign-in to an existing user account
    events:
      - httpApi:
          path: /api/auth/login
          method: POST
